language: python 
dist: trusty
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
# command to run tests
script: python peerfinder.py --asn 6507 15133 
