language: python 
sudo: false
cache: pip
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.8-dev
      env: TOXENV=py38
    - python: pypy
install:
  - pip install -r requirements.txt
# command to run tests
script: python peerfinder.py --asn 6507 15133 

